<?php

namespace UserBundle\Repository;

use UserBundle\Entity\Tokens;

/**
 * TokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokensRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveToken(Tokens $token)
    {
        $this->_em->persist($token);
        $this->_em->flush();
        return $token;
    }

    public function removeToken(Tokens $token)
    {
        $this->_em->remove($token);
        $this->_em->flush();
    }

}
