services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.user_serializer:
          class: UserBundle\Service\UserSerializer
          arguments: ['@doctrine.orm.entity_manager']